# Generated by Django 3.0.8 on 2020-07-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='timetable',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
    ]
