# Generated by Django 3.0.8 on 2020-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubaccount',
            name='verified',
        ),
    ]
