# Generated by Django 3.0.8 on 2020-07-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_clubaccount_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigRecruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date_time', models.DateTimeField(null=True)),
                ('rec_desc', models.TextField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubBigEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_desc', models.TextField(default='', max_length=1000, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='clubs/events')),
                ('event_url', models.URLField(default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='club_logo',
            field=models.ImageField(default='', null=True, upload_to='clubs/logos'),
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date_time', models.DateTimeField(null=True)),
                ('rec_desc', models.TextField(default='', max_length=1000, null=True)),
                ('club_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=100, null=True)),
                ('event_desc', models.TextField(default='', max_length=1000, null=True)),
                ('event_poster', models.ImageField(default='', null=True, upload_to='clubs/events')),
                ('event_url', models.URLField(default='', null=True)),
                ('club_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubAccount')),
            ],
        ),
    ]
